2020-12-16 14:28:24 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0541EA50>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0541EA50>
2020-12-16 14:28:24 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0541EA50>
2020-12-16 14:32:31 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0518FA90>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0518FA90>
2020-12-16 14:32:31 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0518FA90>
2020-12-16 14:33:57 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:33:57 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:34:48 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:34:48 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:38:41 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x05BB0AF0>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x05BB0AF0>
2020-12-16 14:38:41 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x05BB0AF0>
2020-12-16 14:38:52 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x04F9ECF0>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 56, in insert
    return await self.write_mysql_db.create(self.model, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 193, in create
    pk = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x04F9ECF0>
2020-12-16 14:38:52 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x04F9ECF0>
2020-12-16 14:39:25 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x050D0470>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x050D0470>
2020-12-16 14:39:25 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x050D0470>
2020-12-16 14:41:14 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x054BFAD0>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x054BFAD0>
2020-12-16 14:41:14 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x054BFAD0>
2020-12-16 16:13:52 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 255, in delete
    return await self.write_mysql_db.delete(obj=obj)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 251, in delete
    query = obj.delete().where(obj._pk_expr())
AttributeError: 'coroutine' object has no attribute 'delete'
2020-12-16 16:13:52 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:03 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 255, in delete
    return await self.write_mysql_db.delete(obj=obj)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 251, in delete
    query = obj.delete().where(obj._pk_expr())
AttributeError: 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:03 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:55 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 255, in delete
    return await self.write_mysql_db.delete(obj=obj)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 251, in delete
    query = obj.delete().where(obj._pk_expr())
AttributeError: 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:55 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
2020-12-16 16:18:26 [fileLogger] [ERROR] : '>' not supported between instances of 'dict' and 'int'
2020-12-16 16:22:01 [fileLogger] [ERROR] : type object 'User' has no attribute 'io'
2020-12-16 16:23:04 [fileLogger] [ERROR] : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")
Traceback (most recent call last):
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1448, in _run_sql
    await cursor.execute(operation, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 183, in list_paginate
    results = await self.read_mysql_db.execute(sql)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 272, in execute
    return (await execute(query))
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 432, in execute
    return (await coroutine(query))
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 570, in select
    cursor = await _execute_query_async(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1465, in _execute_query_async
    return (await _run_sql(database, *query.sql()))
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1453, in _run_sql
    return cursor
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee.py", line 2831, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1448, in _run_sql
    await cursor.execute(operation, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
peewee.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")
2020-12-16 16:23:04 [fileLogger] [ERROR] : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")
